### ISSUE TITLE
can I append my character lora to the workflow?

### ISSUE THREAD

**Issue by codexq123** [MrForExample/ComfyUI-AnimateAnyone-Evolved#10]
Can I append my character lora to MooreAnimateAnyone_DDIM.json workflow to get a better result?

**Comment by MrForExample** [comment]
You can append your character lora, but I doubt you will get better result, since the model is trained to follow the reference image closely, meaning your reference defines the style of the output, so lora will mostly likely barely does anything or entirely nothing
