### ISSUE TITLE
3d node import fail

### ISSUE THREAD

**Issue by manassm** [MrForExample/ComfyUI-AnimateAnyone-Evolved#12]
I am on windows. I have been trying to run sample workflow but kept getting 3d node import fail.
I tried to install it through comfy manager, did "pip install -r requirement", and downloaded necessary files to appropriate folders.
also tried doing pip install --upgrade diffusers, but didn't help.
![스크린샷 2024-01-29 133147](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/70854401/808494d0-caf2-4b39-96d8-4956dc525cab)
![스크린샷 2024-01-29 132740](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/70854401/6d982335-6815-453d-b17d-16eba40faec4)

**Comment by manassm** [comment]
here is my comfyui boot log:

C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto
** ComfyUI startup time: 2024-01-29 13:30:38.398546
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32540 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 19, in <module>
    from .algorithms.main_3DGS import GaussianSplatting, GSParams
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS.py", line 11, in <module>
    from .main_3DGS_renderer import Renderer
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\algorithms\main_3DGS_renderer.py", line 26, in <module>
    from diff_gaussian_rasterization import (
ModuleNotFoundError: No module named 'diff_gaussian_rasterization'

Cannot import C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'diff_gaussian_rasterization'
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Traceback (most recent call last):
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import PixArtAlphaTextProjection
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)
### Loading: ComfyUI-Impact-Pack (V4.56)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.6)
### ComfyUI Revision: 1936 [9321198d] | Released on '2024-01-29'
------------------------------------------------
Comfyroll Custom Nodes v1.55 :  165 Nodes Loaded
------------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
FizzleDorf Custom Nodes: Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Requirement already satisfied: segment_anything in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: timm in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.9.12)
Requirement already satisfied: addict in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: yapf in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.40.2)
Requirement already satisfied: torch>=1.7 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (2.1.2+cu121)
Requirement already satisfied: torchvision in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.16.2+cu121)
Requirement already satisfied: pyyaml in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: huggingface-hub in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.19.4)
Requirement already satisfied: safetensors in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: importlib-metadata>=6.6.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (7.0.1)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: zipp>=0.5 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata>=6.6.0->yapf->-r requirements.txt (line 4)) (3.17.0)
Requirement already satisfied: filelock in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.13.1)
Requirement already satisfied: typing-extensions in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: sympy in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (1.12)
Requirement already satisfied: networkx in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: fsspec in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (2023.12.2)
Requirement already satisfied: requests in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: packaging>=20.9 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: numpy in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: colorama in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.7->timm->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm->-r requirements.txt (line 2)) (1.3.0)
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is the only way to run away without leaving home." - Twyla Tharp


Import times for custom nodes:
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip_text_encode_split.py
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-yanc
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Moore-AnimateAnyone
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.1 seconds (IMPORT FAILED): C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds (IMPORT FAILED): C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   0.5 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor
   1.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.8 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by hypercryptoman** [comment]
just type diffusers in install pip packages in comfyui manager worked for me. tried for hours !!! this post and typing it in fixed any issues i was having!

**Comment by manassm** [comment]
typing "diffusers" in "install pip packages" in manger worked for me too. Thanks for help.

**Comment by jshay21** [comment]
Yes, I tried the fix above, but am still getting the error:

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): E:\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved

**Comment by sbalani** [comment]
I'm still getting this issue too. Tried pip diffusers. still not working.

**Comment by CoraAI** [comment]
> I'm still getting this issue too. Tried pip diffusers. still not working.

+1. looking for help here, thanks in advance.

**Comment by bluehood2022** [comment]
Damn, I had the same problem and spent a lot of time looking for a solution
