### ISSUE TITLE
 Cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by zeta274** [MrForExample/ComfyUI-AnimateAnyone-Evolved#15]
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import PixArtAlphaTextProjection
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

**Comment by corvo4791** [comment]
You probably have installed another version of ANIMATE ANYONE: "ComfyUI-Moore-AnimateAnyone"
Delete the folder "ComfyUI-Moore-AnimateAnyone" and install "ComfyUI-AnimateAnyone-Evolved".

**Comment by ctankep** [comment]
You need to update " diffusers " to `0.25.1` ,
Eg. `pip --install upgrade diffusers' will add the new embedding ..
—  I had the same issue yesterday ..

**Comment by corvo4791** [comment]
> You need to update " diffusers " to `0.25.1` , Eg. `pip install --upgrade diffusers==0.25.1` will add the new embedding .. Then " PixArtAlphaTextProjection " can be found !

I did it but this didn't solve the problem. When I send the command: "pip install --upgrade diffusers==0.25.1" Diffusers is installed in Python's "site-packages" folder (the one located in: C:\Users\USERNAME\AppData\Local\Programs\Python\Python310)
Maybe, Diffusers must be installed in the "site-packages" of the "python_embeded". If yes, how do I do it?

Thanks

**Comment by zeta274** [comment]
> > You need to update " diffusers " to `0.25.1` , Eg. `pip install --upgrade diffusers==0.25.1` will add the new embedding .. Then " PixArtAlphaTextProjection " can be found !
> 
> I did it but this didn't solve the problem. When I send the command: "pip install --upgrade diffusers==0.25.1" Diffusers is installed in Python's "site-packages" folder (the one located in: C:\Users\USERNAME\AppData\Local\Programs\Python\Python310) Maybe, Diffusers must be installed in the "site-packages" of the "python_embeded"?
> 
> If yes, how do I do it?
> 
> Thanks



Yes, this is the solution, but first, navigate to Python_Embeded and use the Python executable there. So, in that folder:
``` python.exe -m pip install --upgrade diffusers==0.25.1```


Important: After doing this, everything worked, however, I had to replace certain modules from the Impact pack with their newer variants that are roughly identical.

**Comment by corvo4791** [comment]
> python.exe -m pip install --upgrade diffusers==0.25.1

DUUUUUDE!!! You saved my life.
Everything works perfectly, now. No error messages. 
THANKS. I'm struggling since yesterday.

**Comment by TomTomGit86** [comment]
i think im facing simillar problems related to this fix but with comfyui, and the animate anyone addon/plugin. i ran the update diffusers in the pythong embeded forlder of comfyui install but didnt solve my issue and got this message when running the update:

DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

anythoughts how to fix ?

**Comment by corvo4791** [comment]
> i think im facing simillar problems related to this fix but with comfyui, and the animate anyone addon/plugin. i ran the update diffusers in the pythong embeded forlder of comfyui install but didnt solve my issue and got this message when running the update:
> 
> DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at [pypa/pip#12063](https://github.com/pypa/pip/issues/12063)
> 
> anythoughts how to fix ?

It is written in Yellow, right. This also happens to me and I think you can ignore it.

**Comment by TomTomGit86** [comment]
Right ok but this still hasn't fixed my issue with the nodes in animate anyone to be able to use different samplers I know this isn't strictly the thread for that issue but seems similar programs/code have similar issues

**Comment by ctankep** [comment]
Hi ,

> DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at [pypa/pip#12063](https://github.com/pypa/pip/issues/12063)


This is just saying that `torch 0.2.5` has a non standard version specifier that is throwing this " deprecation " warning
that you can ignore. The fault is because there is an asterisk  which won't be recognised once " pip " updates to the next major version and removes support for that and will throw an error.

The issue needs to be fixed in the `torchsde` repo and the meta data for that package. It's happening because the original maintainers from " google " moved on , and left " torchsde " as a community maintained project. There is a simple one line fix but nobody has merged the PR for it. You can fix it on your end to remove the warning though next time you install `torchsde` it will be there :

—  Remove the " .* " inside " torchsde-0.2.5.dist-info\METADATA " file :
`Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"`

—  Issue #131 " Malformed Torch SDE package " :
[ [torchsde-0.2.5.dist-info\METADATA](torchsde-0.2.5.dist-info\METADATA) ]

**Comment by corvo4791** [comment]
> Hi ,
> 
> > DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at [pypa/pip#12063](https://github.com/pypa/pip/issues/12063)
> 
> This is just saying that `torchsde 0.2.5` has a non standard version specifier that is throwing this " deprecation " warning that you can ignore. The fault is because there is an asterisk which won't be recognised once " pip " updates to the next major version and removes support for that and will throw an error.
> 
> The issue needs to be fixed in the `torchsde` repo and the metadata for that package. It's happening because the original maintainers from " google " moved on , and left it as a community maintained project. There is a simple one line fix that has been merged months ago but no new updated version released. You can fix it on your end to remove the warning though next time you install `torchsde 0.2.5` it will be there :
> 
> — Remove the " .* " inside `torchsde-0.2.5.dist-info\METADATA` : Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"
> 
> — Issue #131 " Malformed Torch SDE package " : [[google-research/torchsde#131](https://github.com/google-research/torchsde/issues/131)]

In my METADATA there's also this: Requires-Dist: scipy (==1.5.*) ; python_version < "3.7"

Should I also correct it deleting .*, there?
