### ISSUE TITLE
The script fail to load!

### ISSUE THREAD

**Issue by merecesarchviz** [MrForExample/ComfyUI-AnimateAnyone-Evolved#16]
Hi i install it from the comfyui manager and i got this issue "The torch environment may be compromised due to version issues as some torch-related packages are being reinstalled" and the script in the cmd window shows as import failed!

anyone had this problem and solve it?
![fail](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/79140456/661c6883-7986-4f07-9743-f4becaa6d517)

**Comment by corvo4791** [comment]
That's another version of ANIMATE ANYONE. Delete the folder "ComfyUI-Moore-AnimateAnyone" and install "ComfyUI-AnimateAnyone-Evolved".

**Comment by ctankep** [comment]
All these re - packaged " diffusers " plugins are screwed ..   
Then also depend on different versions of that for specific features. I understand the rush to get this out , but if the install is broken - and the plug in is basically 20 - 100 Gb of " diffusers " then it's not really a plug in per se. Its basically installing another complete " stable diffusion " pipeline inside a " comfy ui " sub folder ..
